training:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 2
  per_device_eval_batch_size: 1
  gradient_checkpointing: True
  eval_accumulation_steps: 1
  optim: paged_adamw_32bit
  save_steps: 2
  logging_steps: 2
  learning_rate: 5e-7
  bf16: True
  max_grad_norm: 0.3
  num_train_epochs: 1
  warmup_ratio: 0.03
  lr_scheduler_type: cosine
  evaluation_strategy: steps
  eval_steps: 2
  report_to: wandb
  seed: 42
model:
  id: NousResearch/Nous-Hermes-2-Mistral-7B-DPO
  max_seq_length: 1024
